version: "3.9"

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.21.0-alpine
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./:/app
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  db:
    image: postgres:16.2
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-app}
        POSTGRES_USER: ${POSTGRES_USER:-root}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: 'none'

volumes:
  db:
    driver: local
