services:
  php:
    container_name: symfony-docker-template
    build: .docker/php
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      PHP_IDE_CONFIG: 'serverName=app'
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    tty: true

  db:
    image: postgres:16.3
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
        POSTGRES_DB: ${POSTGRES_DB:-app}
        POSTGRES_USER: ${POSTGRES_USER:-root}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: 'none'

volumes:
  caddy_data:
  caddy_config:
  db:
    driver: local
