version: "3.9"

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    user: "1000:1000"
    volumes:
      - ./server:/var/www/server

  nginx:
    image: nginx:1.21.0-alpine
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/server
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    logging:
      driver: 'none'

volumes:
  db:
    driver: local
